name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: receita
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Run tests
        run: mvn test
        env:
          SPRING_PROFILES_ACTIVE: test
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/contador-receita-back:latest

  deploy-oracle:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Oracle Cloud VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ORACLE_VPS_HOST }}
          username: ${{ secrets.ORACLE_VPS_USERNAME }}
          key: ${{ secrets.ORACLE_VPS_PRIVATE_KEY }}
          port: ${{ secrets.ORACLE_VPS_SSH_PORT }}
          script: |
            rm -rf {{ {{ secrets.PROJECT_DIR }} }}
            git clone https://github.com/FernandoAurelius/contador-comite-back.git {{ secrets.PROJECT_DIR }}

            cp ~/.env {{ secrets.PROJECT_DIR }}/.env

            cd {{ secrets.PROJECT_DIR }}

            sudo docker compose down || true
            sudo docker compose pull
            sudo docker compose up -d

            sudo docker ps
